### ISSUE TITLE
Can't compile on Ubuntu 17.10

### ISSUE THREAD

**Issue by salvadhor** [cseyve/tamanoir#1]
Hi,

New Ubuntu 17.10 doesn't have any package that contains opencv2/legacy/compat.hpp (or even compat.hpp):

In file included from src/imgproc.cpp:32:0:
inc/imgutils.h:78:10: fatal error: opencv2/legacy/compat.hpp: No such file or directory

Can it be fixed?

**Comment by cseyve** [comment]
I think it is because Ubuntu switched to OpenCV 3. The current version of Tamanoir is still using the C API, so OpenCV2.4 packages. 

I don't have time right now, maybe if you can opend some time to help changing the dependencies.
